# Generated by Django 2.2.11 on 2020-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenvalidation',
            name='token_valid',
            field=models.BooleanField(default=False),
        ),
    ]
