# Generated by Django 2.2.11 on 2020-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appregister',
            name='first_token_check',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
