# Generated by Django 2.2.11 on 2020-04-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_server', '0002_auto_20200402_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='appregister',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appregister',
            name='client_host',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
